- src/contract.rs
- src/msg.rs
- src/query.rs
- src/state.rs
This PR closes https://github.com/JakeHartnell/cw-dao/issues/1. 
The dao can now be configured to require a deposit to make a proposal. The deposit is returned if the proposal passes and becomes property of the dao if the proposal fails. 
This change will require future work to prevent the dao from accidentally spending proposal deposit funds. This will most likely be implemented by having a separate contract for managing the deposit funds to make the distinction more clear. 
This PR also persists the proposer's address to the proposal state object. This was necessary to return the proposal deposit and seems generally useful.
> Optionally require a deposit to make a proposal

- .cargo/config
- .github/workflows/basic.yml
- Cargo.lock
- README.md
- contracts/cw-dao/Cargo.toml
- contracts/cw-dao/src/contract.rs
- contracts/cw20-gov/examples/schema.rs
- contracts/cw20-gov/schema/balance_at_height_response.json
So this uses the new cw20-gov token and the new `BalanceAtHeight` query. Similary to compound, when someone votes it checks their balance at the start of the proposal.
Closes #17.
Also added some more CI stuff and updated the schema.
> Use BalanceAtHeight

- docker/app.toml
- scripts/deploy_local.sh
This change adds the custom app.toml script as the right time in the build in order to enable the REST api.
> Fix setting customer app.toml docker build script

- README.md
- scripts/deploy_local.sh
Removes ambiguity about which address to place in which .env.local field. 
(This issue is related to #50)
> Make variable names in deploy script match those in `cw-dao-dapp` env.local

- contracts/stake-cw20/src/contract.rs
- contracts/stake-cw20/src/error.rs
- contracts/stake-cw20/src/state.rs
There exists a world wherein a user of the staking contract creates so many claims that the process of iterating over them to redeem them causes an out of gas error.
Ideally, we'd sidestep this issue by adding the ability to redeem a single claim to the contracts. Sadly, cw-controllers has [no such](https://docs.rs/cw-controllers/latest/cw_controllers/struct.Claims.html) method and the fields of `Claims` are private. Short of submitting a change there we can limit the number of outstanding claims allowed.
Open to thoughts on if this is the approach we'd like to take. Ideal one is certainly to modify cw-controllers to allow this sort of behavior.
Want to verify that 100 claims is a conservative enough threshold that one can still submit a claim that that point.
1. Spin up contracts in …
> Don't allow creation of claims if >= 100 are outstanding

- contracts/stake-cw20-gov/Cargo.toml
- contracts/stake-cw20-gov/src/contract.rs
Updates the staking contract version used by the gov token staking contract so that the `MAX_CLAIMS` changes will take effect.
> Use latest staking contract version in gov staking contract

- contracts/cw3-dao/src/contract.rs
- contracts/cw3-dao/src/msg.rs
- contracts/cw3-dao/src/tests.rs
Needed to provide a migration path for DAOs when new and better staking contracts inevitably come out.
> Add UpdateStakingContract method and tests

- Cargo.lock
- contracts/cw3-dao/Cargo.toml
- contracts/cw3-dao/src/contract.rs
- contracts/stake-cw20/Cargo.toml
- contracts/stake-cw20/schema/execute_msg.json
- contracts/stake-cw20/schema/get_config_response.json
- contracts/stake-cw20/schema/instantiate_msg.json
- contracts/stake-cw20/src/contract.rs
- contracts/stake-cw20/src/error.rs
- contracts/stake-cw20/src/msg.rs
- contracts/stake-cw20/src/state.rs
This contract is more widely useful then just DAO's and therefore I think it is best if admin is optional. When an admin is not set the staking configs are immutable. This is an important user safeguard as the admin can lock the users funds forever and it could be quite dangerous if the admin was malicious.
> Make admin optional stake cw20

- contracts/cw3-dao/src/contract.rs
- contracts/cw3-dao/src/helpers.rs
- contracts/cw3-dao/src/query.rs
- contracts/cw3-dao/src/tests.rs
The amount of voting power a given address has in a proposal is determined by their voting power on the block when the proposal as started. We currently do not expose this information via proposal queries which makes it quite the detective operation to determine if a given address can vote in a proposal.
> Add `start_height` field to proposal queries

- scripts/deploy_local.sh
This adds support for building on M1+ Macs.
Additionally, `pr-135` is no longer reflective of the latest `junod`, so has been bumped.
I've tested that this builds on:
- M1 Pro
- AMD Threadripper
Would appreciate one Apple Silicon and one amd64 reviewer to make sure this still builds.
> feat: adds Apple Silicon support, updates junod to v2.1.0 in deploy_local

- contracts/cw3-dao/src/state.rs
- contracts/cw3-dao/src/tests.rs
- contracts/cw3-multisig/src/state.rs
- contracts/cw3-multisig/src/tests.rs
Addresses Issue #169 
Adds an is_rejected method to both Proposal types which does the same as is_passed however checks no votes for a majority.
Added unit tests  for the logic on the Proposal side.
Added integration tests for both a DAO and Multisig.
Feedback appreciated.
> Reject proposals when they cannot pass

- contracts/cw3-dao/src/contract.rs
- contracts/cw3-dao/src/msg.rs
- contracts/cw3-dao/src/state.rs
- contracts/cw3-dao/src/tests.rs
- contracts/cw3-multisig/src/contract.rs
- contracts/cw3-multisig/src/msg.rs
- contracts/cw3-multisig/src/state.rs
- contracts/cw3-multisig/src/tests.rs
Addresses #176 
Allows DAOs/multisigs to automatically list CW20s sent to them.
- Both DAOs and multisigs can have a config flag to disable/enable this feature e.g. big DAOs may not want to be spammed with CW20s.
- Automatically adding to the tracked balances state.
Feedback appreciated!
> Automatically add cw20s to balance list

- contracts/cw3-dao/src/contract.rs
- contracts/cw3-dao/src/msg.rs
- contracts/cw3-dao/src/tests.rs
- contracts/cw3-multisig/src/contract.rs
- contracts/cw3-multisig/src/msg.rs
- contracts/cw3-multisig/src/tests.rs
- contracts/stake-cw20/src/contract.rs
- contracts/stake-cw20/src/msg.rs
The Addr type is not validated during deserialization yet it still
implements both serialization and deserialization. This means that an
invalid Addr can be constructed in the event that it is passed to a
contract via a message.
This removes all usage of Addr in message types. Before this change
two bugs are present:
1. For the DAO and Multisig contracts tokens can be added to the
treasury which are invalid.
2. For the staking contract this allows setting the admin of the
contract to an invalid address.
> Remove usage of Addr in contract messages.

- contracts/cw3-dao/src/contract.rs
- contracts/cw3-dao/src/error.rs
- contracts/cw3-dao/src/msg.rs
- contracts/cw3-dao/src/state.rs
- contracts/cw3-dao/src/tests.rs
We now have an added enum in instantiate to create a DAO with an existing staking contract.
- Similar to how we handle CW20s.
- If we instantiate a new CW20 the contract will error if the user specifies to use an existing staking contract. As this action is invalid
- Existing CW20s can use both a new staking contract or an older one
- Test cases cover all possible combinations
Feedback appreciated.
> Instantiate DAO with existing staking contract

- contracts/cw20-staked-balance-voting/schema/instantiate_msg.json
- contracts/cw20-staked-balance-voting/schema/query_msg.json
- contracts/cw20-staked-balance-voting/src/contract.rs
- contracts/cw20-staked-balance-voting/src/msg.rs
- contracts/cw20-staked-balance-voting/src/tests.rs
Resolves #208 
Sending part of the initial token supply to the DAO was left out of the contract v1 rewrite. This adds it back in.
> Add DAO initial balance to staked governance token instantiation

- contracts/cw-govmod-single/src/contract.rs
- contracts/cw-govmod-single/src/msg.rs
- contracts/cw-govmod-single/src/query.rs
- contracts/cw-govmod-single/src/tests.rs
- contracts/cw-govmod-single/src/threshold.rs
- contracts/cw20-staked-balance-voting/Cargo.toml
- contracts/cw4-voting/Cargo.toml
Resolves #213 
This adds the `ReverseProposals` query to `cw-govmod-single`. It does not add the `Tally` query as in the new design that query is strictly a subset of the `Proposal` query with a little extra work to compute the current turnout percent on the contract side.
Where possible we want to limit the amount of contract side compute happening and limit complexity in the contracts so I'm in favor of just not adding it.
> Add `ReverseProposals` query to cw-govmod-single.

- contracts/cw-govmod-single/src/proposal.rs
- contracts/cw-govmod-single/src/tests.rs
- contracts/cw-govmod-single/src/threshold.rs
- packages/voting/src/lib.rs
The majority threshold option allows the creator to specify that they
would like a proposal to pass if the majority of votes for that
proposal are yes. Otherwise, a proposal will pass if the yes votes are
greater than or equal to the number of votes required for passing.
Why this is needed:
If the passing threshold is 60% folks likely expect that if 6 out of
10 members vote yes that proposal will pass. This implies that yes >=
threshold.
On the other hand, this makes it difficult to specify that users would
like a majority of votes to be the passing threshold as specifying a
50% passing threshold will allow a vote with 5 yes and 5 no votes to
pass. The majority option addresses this by comparing yes > threshold
for that case.
This PR also adds a special case so if all the votes for a …
> Add a majority passing threshold option.

- contracts/cw-governance/schema/dump_state_response.json
- contracts/cw-governance/schema/execute_msg.json
- contracts/cw-governance/schema/instantiate_msg.json
- contracts/cw-governance/schema/query_msg.json
- contracts/cw-governance/src/contract.rs
- contracts/cw-governance/src/error.rs
- contracts/cw-governance/src/msg.rs
- contracts/cw-governance/src/state.rs
- contracts/cw-governance/src/tests.rs
- contracts/cw-govmod-single/src/tests.rs
Part 2 of #214
Allow the DAO to set an initial list of items on instantiation. These items can be:
- already existing addresses
- info used to instantiate a new contract, storing the corresponding address automatically
> Initial items on DAO Instantiation

- Cargo.lock
- contracts/cw-governance/Cargo.toml
- contracts/cw-governance/src/contract.rs
- contracts/cw-governance/src/msg.rs
- contracts/cw-governance/src/query.rs
- contracts/cw-governance/src/state.rs
- contracts/cw-governance/src/tests.rs
- contracts/cw-govmod-single/src/tests.rs
Adds:
1. Management of cw20 and cw721 token lists.
2. Automatic addition of received cw20 and cw721 assets to list.
3. Toggling on / off of automatic addition.
4. Associated queries for listing assets and listing asset balances.
After some thinking I've opted to implement this functionality inside
of the core contract instead of inside separate treasury
modules. Implementing treasury modules is nice because it makes us
flexible in the event that a new token / NFT / unknown asset standard
comes out and we would like to support it. It adds a fair amount of
complexity though:
1. Someone wanting to send tokens to a DAO must send those tokens to
the appropriate treasury contract.
2. Queries on the frontend for asset lists require two additional
queries (what are treasury contracts, what is …
> Add cw-governance functionality for managing cw20 and cw721 assets.

- contracts/cw3-dao/src/state.rs
- contracts/cw3-multisig/src/state.rs
Need to get some eyes on this to check my logic all works clear.
New logic is no votes can reject proposals when they are greater than 1 - threshold. (Or for absolute count total_weight - count). 
Going to need some eyes on this to sanity check.
> Fix threshold for no for non v1 side contracts

- contracts/stake-cw20-external-rewards/src/contract.rs
Helping this PR along - removed the test_math function which was causing lint errors and appeared to be just for experimentation
> Fix lint for external staking rewards PR

- contracts/cw-proposal-single/src/proposal.rs
- packages/voting/src/lib.rs
For the majority threshold instead of checking if `votes > threshold /
2`
we can instead check if `votes * 2 > threshold`. This removes a
division and means that we don't have to worry about a round down in
the division reporting a majority before one has actually been
obtained.
This also removes the `votes_needed` function which is no longer used
and adds a number of new tests to make sure this logic is working as
expected.
> Remove division when computing if majority threshold is reached.

- contracts/stake-cw20-external-rewards/src/contract.rs
this contract was failing to instantiate if optional values were not given as it would try to make a response msg attribute with and empty string which is invalid.
> fix empty attribute bug in external staking contract

- contracts/cw20-staked-balance-voting/src/contract.rs
- contracts/cw20-staked-balance-voting/src/msg.rs
- contracts/cw20-staked-balance-voting/src/tests.rs
This was previously in the top level instantiate message but had not
effect if the contract was instantiated with an existing staking
contract.
> Move initial DAO balance into `TokenInfo::New`.

- contracts/cw-named-groups/Cargo.toml
- contracts/cw-proposal-single/src/contract.rs
- contracts/cw-proposal-single/src/msg.rs
- contracts/cw-proposal-single/src/proposal.rs
- contracts/cw-proposal-single/src/tests.rs
- contracts/proposal-hooks-counter/src/tests.rs
The `latest` field previously allowed a proposal to be created that
expires before the default proposal voting period. When a DAO has a
quorum this makes the hostile takeover cost`quorum * threshold * token_price`
as a proposer could create a proposal that instantly
expires and vote on it in one block.
> Remove latest field from Proposal

- contracts/stake-cw20-external-rewards/src/contract.rs
This bug was breaking the contract when rewards were low. Fixed the bug and added a test for this edge case.
We use a scale factor when dividing the rewards accured during a time period and the total staked to ensure the numerator is always larger then the denominator. We then unscale this value when we calculate the rewards earned by a user. The issue here was we were unscaling too early and were running into issues where the value was lower then the scale factor resutling in zero pending rewards.
This PR also removes the unecessary use of uint512. When calculating the rewards the total rewards accrued during a certain time period we do not need to worry about this value overflowing a u128. Given the total amount of tokens is bound by a u128 and rewards accrued cannot excced the total …
> Staking external rewards scale factor bug

- contracts/cw-proposal-single/src/contract.rs
- contracts/cw-proposal-single/src/error.rs
The Juno mainnet allows storage writes in execute messages that are
larger than the amount of data queryable in a query message. This
means that a sufficiently large proposal (around 40,000 bytes) will
be unqueriable after being created.
To prevent this, this commit limits the size, in bytes, that a proposal
may be. A sensible limit for this size was found by repeatedly storing
a contract on the mainnet and creating the largest possible proposal.
> Limit the size of proposals.

- contracts/stake-cw20-external-rewards/src/contract.rs
- contracts/stake-cw20-external-rewards/src/error.rs
Bug in contract where if reward config results in rewards less then 1 to block the reward rate is rounded down to zero and the tokens are locked. Fixed by throwing an error if the funding configs result in a zero reward rate.
> Stake CW20 External Rewards: Sub zero reward rate bug

- contracts/cw-core/src/contract.rs
- contracts/cw-core/src/error.rs
- contracts/cw-core/src/helpers.rs
- contracts/cw-core/src/msg.rs
- contracts/cw-core/src/state.rs
- contracts/cw-core/src/tests.rs
- contracts/cw-proposal-single/src/tests.rs
- contracts/proposal-hooks-counter/src/tests.rs
Noticed that we had missed some renaming when I was instantiating the latest contracts.
> Rename governance modules -> proposal modules in cw-core messages.

- contracts/cw-proposal-single/src/tests.rs
Little fix. Think Github neglected to re-run CI when the offending PR was merged.
> Fix test error.

- contracts/cw-core/examples/schema.rs
- contracts/cw-core/schema/dump_state_response.json
- contracts/cw-core/schema/execute_msg.json
- contracts/cw-core/schema/pause_info_response.json
- contracts/cw-core/schema/query_msg.json
- contracts/cw-core/src/contract.rs
- contracts/cw-core/src/error.rs
- contracts/cw-core/src/msg.rs
- contracts/cw-core/src/query.rs
- contracts/cw-core/src/state.rs
- contracts/cw-core/src/tests.rs
Stops literally all execute messages from happening for the duration of the pause.
> Allow the core contract to pause itself.

- contracts/stake-cw20/src/contract.rs
It is important that we maintain this invariant to protect against flash loan hostile takeover attacks.
> Add test to assert that we do not reflect staked balances until the following block.

- contracts/cw20-staked-balance-voting/src/contract.rs
- contracts/cw20-staked-balance-voting/src/error.rs
- contracts/cw20-staked-balance-voting/src/tests.rs
Closes #269 
Validate absolute count against the token total supply to prevent potential bricking.
Feedback appreciated.
> Check absolute count active threshold is not greater than total supply

- contracts/cw-core/src/contract.rs
- contracts/cw-core/src/state.rs
- contracts/cw-core/src/tests.rs
Storing this led to a state inconsistency when we would update it's
value when the update_proposal_modules method was called. At that
point we would update its value, but the new modules would not
actually be installed as the submessages to add them had not been
executed.
It turns out that we can enforce that there is always a proposal
module in constant time without having that state. This just removes
it in favor of that method.
> Remove `PROPOSAL_MODULES_COUNT` state.

- contracts/stake-cw20-reward-distributor/schema/execute_msg.json
- contracts/stake-cw20-reward-distributor/src/contract.rs
- contracts/stake-cw20-reward-distributor/src/msg.rs
- contracts/stake-cw20-reward-distributor/src/tests.rs
This new execute message allows the owner to reclaim the reward funds. This would be used by a DAO that wants to change something significant about how rewards are being distributed such as lowering by a large amount or change the contract.
> Add withdraw method to stake-cw20-reward-distributor

- contracts/stake-cw20-reward-distributor/src/contract.rs
- contracts/stake-cw20-reward-distributor/src/error.rs
- contracts/stake-cw20-reward-distributor/src/tests.rs
This PR includes a bunch of random fixs for the rewards distribution contract. 
This PR remove `out_of_funds` and `no_pending_payments`. Instead of pushing an error the contract will just not distribute any funds, but still update the `last_payment_block` variable to the current block. This imo is a better behavior for when the contract is out of funds. With these errors, when the contract is refunded it will have to pay out for all the previous blocks. 
This PR makes it so a distribution happens before config is updated. I feels updating the config should not affect blocks in the past. In current implementation if I update the config and a distribution hasn't occured for a while, when I update the config these undistributed past blocks will be paid at the new updated rate.
This PR also …
> Remove errors and make update config force a distributions stake-cw20-reward-distributor

- contracts/cw-proposal-single/src/contract.rs
- contracts/cw-proposal-single/src/error.rs
- contracts/cw-proposal-single/src/tests.rs
This upstreams two important security fixes for our single choice proposals module. These changes have already been applied for all the DAOs currently using these contracts.
> Prevent multiple executions of proposals and closing of passed proposals.

- contracts/cw-core/schema/dump_state_response.json
- contracts/cw-core/schema/execute_msg.json
- contracts/cw-core/schema/instantiate_msg.json
- contracts/cw-core/schema/query_msg.json
- contracts/cw-core/src/contract.rs
- contracts/cw-core/src/query.rs
- contracts/cw-core/src/state.rs
- contracts/cw-core/src/tests.rs
- contracts/cw-proposal-single/src/staking_tests.rs
- contracts/cw-proposal-single/src/tests.rs
This removes usage of the old naming "governance modules" from the cw-core contract in favor of the current "proposal modules" naming.
> Remove old naming and update schema for cw-core.

- contracts/cw-proposal-single/schema/config_response.json
- contracts/cw-proposal-single/schema/execute_msg.json
- contracts/cw-proposal-single/schema/instantiate_msg.json
- contracts/cw-proposal-single/schema/list_proposals_response.json
- contracts/cw-proposal-single/schema/proposal_response.json
- contracts/cw-proposal-single/schema/reverse_proposals_response.json
- contracts/cw-proposal-single/src/contract.rs
- contracts/cw-proposal-single/src/error.rs
- contracts/cw-proposal-single/src/msg.rs
- contracts/cw-proposal-single/src/proposal.rs
- contracts/cw-proposal-single/src/staking_tests.rs
- contracts/cw-proposal-single/src/state.rs
- contracts/cw-proposal-single/src/tests.rs
- debug/proposal-hooks-counter/src/tests.rs
- packages/voting/src/threshold.rs
- packages/voting/src/voting.rs
This PR adds a config option to the `cw_proposal_single` contract to allow revoting on proposals. If this config option is toggled:
- Proposals will not be passed or rejected until they have expired.
- Voters may cast new votes before the proposal expires.
> Allow revoting on proposals.

- .github/workflows/audit.yml
This adds a GitHub action that will run `cargo audit` nightly and report any vulnerabilities found by creating a new GitHub issue. Monitoring our dependencies is important because a severe enough issue may mean that we need to release new module versions and have DAOs upgrade.
> Add periodic cargo audit GitHub action.

- README.md
- packages/cw-core-interface/src/voting.rs
This adds a code coverage badge to the README. It also adds a test to the cw-core-interface package to ensure that its query enum is expanded properly by our macros. The badge looks like this:
> Add code coverage badge to README.

- contracts/stake-cw20-external-rewards/src/contract.rs
This PR remove the ability to update the external rewards during the current period. This somewhat unexpectedly will make the contract easier to manage in production. The biggest use case of this contract so far is to give out a certain amount of rewards over a certain time period. Once the time period is over, the reward distributor either wants to continue with the same amount of rewards or modify it. With the ability to add more rewards during the current period, it becomes difficult to continue the rewards at the current rate as if you send your fund message too early, you will accidentally top up the current period. This change makes it so a fund message sent too early will fail. 
With this change a multisig that wants to continue the rewards for another period can set up their fund …
> Simplify external rewards for easier usability

- contracts/stake-cw20-external-rewards/src/contract.rs
- contracts/stake-cw20-external-rewards/src/msg.rs
This will allow us to migrate existing contracts on prod with recent changes.
> Add basic migrate handler to external rewards contract

- contracts/cw-core/examples/schema.rs
- contracts/cw-core/src/contract.rs
- contracts/cw-core/src/msg.rs
- contracts/cw-core/src/tests.rs
- contracts/cw-proposal-single/examples/schema.rs
- contracts/cw-proposal-single/src/contract.rs
- contracts/cw-proposal-single/src/msg.rs
- contracts/cw-proposal-single/src/tests.rs
- contracts/cw20-staked-balance-voting/examples/schema.rs
- contracts/cw20-staked-balance-voting/src/contract.rs
- contracts/cw20-staked-balance-voting/src/msg.rs
- contracts/cw20-staked-balance-voting/src/tests.rs
- contracts/cw4-voting/examples/schema.rs
- contracts/cw4-voting/src/contract.rs
- contracts/cw4-voting/src/msg.rs
- contracts/cw4-voting/src/tests.rs
This will allow our contracts to be migrated by their admin. In the case of modules this is typically the `cw-core` contract.
> Add migrate method to contracts.

- scripts/deploy_local.sh
`rust-optimizer` -> `workspace-optimizer`, uses version `0.12.6`, avoids:
```
... Error during static Wasm validation: Wasm contract doesn't have required export: "instantiate". Exports required by VM: ["allocate", "deallocate", "instantiate"].: create wasm contract failed: invalid request
```
> rust-optimizer -> workspace-optimizer

- contracts/cw-proposal-single/src/contract.rs
- contracts/cw-proposal-single/src/proposal.rs
- contracts/cw-proposal-single/src/tests.rs
Before if no proposals had been created `PROPOSAL_COUNT` would have no
value. This would cause trouble in queries as they would attempt to
load the value and locate nothing causing an error in frontends.
> Initialize PROPOSAL_COUNT to zero.

- Cargo.lock
- contracts/cw-core/Cargo.toml
- contracts/cw-core/schema/get_item_response.json
- contracts/cw-core/schema/instantiate_msg.json
- contracts/cw-core/schema/query_msg.json
- contracts/cw-core/src/contract.rs
- contracts/cw-core/src/msg.rs
- contracts/cw-core/src/query.rs
- contracts/cw-core/src/state.rs
- contracts/cw-core/src/tests.rs
- packages/cw-paginate/Cargo.toml
- packages/cw-paginate/src/lib.rs
Resolves #234 
This makes items a little more flexible and performant. Before we
limited items to being `Addr` types, but this meant that if you wanted
to do something as simple as customize the color of your DAO page you
would need to create a new contract for that and the frontend would
need to make two queries.
This also makes the `list_items` query return key-value pairs so that
the frontend doesn't need to make a second query to get the value of
an item it has determined exists.
> Store items as `String` in cw-core.

- Cargo.lock
- contracts/cw-core/Cargo.toml
- contracts/cw-core/schema/execute_msg.json
- contracts/cw-core/schema/migrate_msg.json
- contracts/cw-core/src/tests.rs
- contracts/cw-proposal-single/Cargo.toml
- contracts/cw-proposal-single/schema/execute_msg.json
- contracts/cw-proposal-single/schema/list_proposals_response.json
- contracts/cw-proposal-single/schema/migrate_msg.json
- contracts/cw-proposal-single/schema/proposal_response.json
- contracts/cw-proposal-single/schema/reverse_proposals_response.json
- contracts/cw-proposal-single/src/tests.rs
When we were trying to create a proposal with a create validator transaction, we found out that we dont currently support the `stargate` field in a [CosmosMsg](https://docs.rs/cosmwasm-std/latest/cosmwasm_std/enum.CosmosMsg.html).
I decided to enable the [ibc3 feature](https://github.com/CosmWasm/cosmwasm/blob/main/packages/std/Cargo.toml#L35), which includes the `stargate` features and the new ibcv3 interchain account stuff.
> Enable ibcv3 feature for cw-proposal-single contract

- contracts/cw4-voting/src/contract.rs
- contracts/cw4-voting/src/tests.rs
I might be pushing my luck here, but it seems  skipping saving when `weight == 0` would work because `query_voting_power_at_height` will return 0 even if the address is missing from storage.
> Audit issue 18

- contracts/stake-cw20-external-rewards/src/contract.rs
Replaces TODO comment with an explanation of why the numbers are they
way they are.
> Replace TODO comment with explanation of why things are the way they are.

- Cargo.toml
Resolves #335 
Adding overflow checks to each profile leads to a ton of warnings during compilation. Seems more likely to confuse folks than to help us. My vote is that we just add this comment and keep our eyes open for accidental removal of overflow checks.
> Add comment explaining overflow checks being important.

- contracts/cw-proposal-single/schema/config_response.json
- contracts/cw-proposal-single/schema/execute_msg.json
- contracts/cw-proposal-single/schema/instantiate_msg.json
- contracts/cw-proposal-single/schema/list_proposals_response.json
- contracts/cw-proposal-single/schema/proposal_response.json
- contracts/cw-proposal-single/schema/reverse_proposals_response.json
- contracts/cw-proposal-single/src/contract.rs
- contracts/cw-proposal-single/src/error.rs
- contracts/cw-proposal-single/src/msg.rs
- contracts/cw-proposal-single/src/proposal.rs
- contracts/cw-proposal-single/src/staking_tests.rs
- contracts/cw-proposal-single/src/state.rs
- contracts/cw-proposal-single/src/tests.rs
- contracts/cw-proposal-single/src/utils.rs
- contracts/cw20-staked-balance-voting/schema/migrate_msg.json
- contracts/cw4-voting/schema/migrate_msg.json
- debug/proposal-hooks-counter/src/tests.rs
This adds a minimum voting period. Having a minimum voting period
allows DAO members some time to respond in the event of a DAO hostile
takeover.
For example, say a DAO exists with some tokens in a LP pool. An
attacker may purchase a large number of those tokens and stake them to
take over the DAO and give the DAO's treasury to themselves. If a
minimum voting period is configured DAO members will have some time to
see this occuring and remove liquidity from the pool to reduce the
amount of damage the attacker might do.
See this issue for some context: https://github.com/DA0-DA0/dao-contracts/issues/356#issuecomment-1154476150
IMO if folks are against this change I'd be happy to just close this PR and
move on. I do think that, on balance, this is probably worth the added
complexity.
> Add min_voting_period to cw-proposal-single.

- contracts/cw-core/examples/schema.rs
- contracts/cw-core/schema/admin_nomination_response.json
- contracts/cw-core/schema/dump_state_response.json
- contracts/cw-core/schema/execute_msg.json
- contracts/cw-core/schema/instantiate_msg.json
- contracts/cw-core/schema/query_msg.json
- contracts/cw-core/src/contract.rs
- contracts/cw-core/src/error.rs
- contracts/cw-core/src/msg.rs
- contracts/cw-core/src/query.rs
- contracts/cw-core/src/state.rs
- contracts/cw-core/src/tests.rs
The new process is as follows:
1. The current admin nominates a new admin.
2. For the nomination to take effect the nominated admin must execute
the `AcceptAdminNomination` method on the core contract.
3. At any point the current admin may withdraw their nomination.
4. The current admin may remove the contract's admin entirely without
any nomination process.
This was suggested by the Oak Security folks and prevents an admin
from accidentally setting the admin of the contract to an invalid
address.
> Update cw-core admin transfer process.

- contracts/cw20-stake-external-rewards/src/contract.rs
- contracts/cw20-stake-external-rewards/src/error.rs
Resolves #327.
Previously a rewards duration of zero was allowed. This is suboptimal because should the admin set a zero rewards duration there are a few places where we'd run into divide by zero errors. This adds the needed checks to be sure a zero reward duration is not set.
> Don't allow zero reward durations.

- contracts/cw20-stake/src/contract.rs
- contracts/cw20-stake/src/msg.rs
This adds a migrate method to `cw20-stake` which allows migration from a beta staking contract to a non-beta staking contract. I have tested this migration using a testnet DAO which can be found here: https://testnet.daodao.zone/dao/juno1m4wsr4wj0hz9uz4kavh0yt8v3ghsf347etqzt66rkqprfn5myajqhw3vpd
> Add migrate method to cw20-stake to allow migration from beta.

- contracts/cw-proposal-single/examples/schema.rs
- contracts/cw-proposal-single/schema/get_vote_response.json
- contracts/cw-proposal-single/schema/query_msg.json
- contracts/cw-proposal-single/src/contract.rs
- contracts/cw-proposal-single/src/msg.rs
- contracts/cw-proposal-single/src/tests.rs
closes: https://github.com/DA0-DA0/dao-contracts/issues/369
I also confirmed that [the generated typescript files](https://github.com/DA0-DA0/dao-contracts/pull/347) are now `yarn build`ing after these changes.
> Rename QueryMsg::Vote -> QueryMsg::GetVote since it causes the typescript generation to break

- contracts/cw-admin-factory/.cargo/config
- contracts/cw-admin-factory/.gitignore
- contracts/cw-admin-factory/Cargo.lock
- contracts/cw-admin-factory/Cargo.toml
- contracts/cw-admin-factory/LICENSE
- contracts/cw-admin-factory/NOTICE
- contracts/cw-admin-factory/README.md
- contracts/cw-admin-factory/examples/schema.rs
- contracts/cw-admin-factory/schema/execute_msg.json
- contracts/cw-admin-factory/schema/instantiate_msg.json
- contracts/cw-admin-factory/schema/query_msg.json
- contracts/cw-admin-factory/src/contract.rs
- contracts/cw-admin-factory/src/error.rs
- contracts/cw-admin-factory/src/lib.rs
- contracts/cw-admin-factory/src/msg.rs
- contracts/cw-admin-factory/src/tests.rs
> add cw-admin-factory contract

- contracts/cw20-stake-external-rewards/src/contract.rs
- contracts/cw20-stake/src/contract.rs
This fixes some lint errors in the stake-cw20 contract. These errors broke CI on main. It appears that happened because clippy added a new lint (we use nightly clippy) as the commit that added the offending lines is three months old.
> Fix lints on stake-cw20.

- contracts/cw-named-groups/src/contract.rs
Clippy was unhappy with:
```rust
if let Err(e) = group {
return Err(e);
}
```
And since we touching this method
extra: `map(|addr|..` looks cleaner this way or we want `String::from`/ `addr.into_string()` here?
> Small changes for `query_dump()`, so it passes clippy and extra

- scripts/deploy_local.sh
This contract was renamed and it broke deploy_local.sh.
> Fix deploy local script to use latest cw20_stake contract name

- Cargo.lock
- contracts/cw-native-staked-balance-voting/examples/schema.rs
- contracts/cw-native-staked-balance-voting/schema/instantiate_msg.json
- contracts/cw-native-staked-balance-voting/schema/owner.json
- contracts/cw-native-staked-balance-voting/src/contract.rs
- contracts/cw-native-staked-balance-voting/src/msg.rs
- contracts/cw-native-staked-balance-voting/src/tests.rs
- contracts/cw-proposal-multiple/src/tests.rs
- contracts/cw-proposal-single/Cargo.toml
- contracts/cw-proposal-single/src/tests.rs
- types/contracts/cw-native-staked-balance-voting/CwNativeStakedBalanceVotingContract.ts
Resolves #419
Also runs `cargo update` to get our dependencies up to date and adds the native token staking voting module to the test suite for `cw-proposal-single` so we've got complete integration tests for that.
> Allow setting owner as instantiator in native token staking.

- contracts/cw-proposal-multiple/schema/config_response.json
- contracts/cw-proposal-multiple/schema/execute_msg.json
- contracts/cw-proposal-multiple/schema/instantiate_msg.json
- contracts/cw-proposal-multiple/schema/list_proposals_response.json
- contracts/cw-proposal-multiple/schema/proposal_response.json
- contracts/cw-proposal-multiple/schema/reverse_proposals_response.json
- contracts/cw-proposal-multiple/src/contract.rs
- contracts/cw-proposal-multiple/src/error.rs
- contracts/cw-proposal-multiple/src/msg.rs
- contracts/cw-proposal-multiple/src/proposal.rs
- contracts/cw-proposal-multiple/src/state.rs
- contracts/cw-proposal-multiple/src/tests.rs
- contracts/cw-proposal-single/src/contract.rs
- packages/voting/src/voting.rs
- types/contracts/cw-proposal-multiple/CwProposalMultipleContract.ts
Closes #367 
Follows the style of revoting implemented on proposal-single
> Revoting multiple

- contracts/cw-core/src/contract.rs
- contracts/cw-proposal-single/schema/migrate_msg.json
- contracts/cw-proposal-single/src/contract.rs
- contracts/cw-proposal-single/src/msg.rs
- contracts/cw-proposal-single/src/state.rs
- contracts/cw-proposal-single/src/tests.rs
- types/contracts/cw-proposal-single/CwProposalSingleContract.ts
Resolves #452
This removes the non-mocked migration test. The test was effectively a
no-op as (so far as I am aware) we don't have a good way worked out to
mock v1 state. The new change errors if the `"config"` key isn't
present wheras the old one would just do nothing if the `"proposals"`
key was not present so the test had to go.
I tried mocking v1 state using the `AppBuilder` from multi-test and
instantiating it with a custom deps. From memory since I deleted the
code (so not real code):
```rust
let mut deps = mock_dependencies();
let v1_item: Item<V1Config> = Item::new("config");
let v1_config = V1Config { /* ... */ };
v1_item.save(&mut deps.storage, &v1_config).unwrap();
let mut app =
AppBuilder::default().with_storage(deps.storage).build(|_, _, _| ());
```
This doesn't work which …
> Add migration for `close_proposal_on_execution_failure` field.

- Cargo.lock
- contracts/cw-core/Cargo.toml
- contracts/cw-proposal-multiple/src/tests.rs
- packages/testing/src/tests.rs
I saw that the cargo audit build [was breaking](https://github.com/DA0-DA0/dao-contracts/runs/8147390503?check_suite_focus=true), and that we also couldn't `cargo update` on main:
```
Updating crates.io index
Updating git repository `[https://github.com/CosmWasm/cw-plus`](https://github.com/CosmWasm/cw-plus%60)
error: failed to select a version for `cosmwasm-std`.
... required by package `cw-multi-test v0.14.0 (https://github.com/CosmWasm/cw-plus?branch=main#24af1b9b)`
... which satisfies git dependency `cw-multi-test` of package `cw-core v0.2.0 (/home/runner/work/dao-contracts/dao-contracts/contracts/cw-core)`
... which satisfies path dependency `cw-core` of package `cw-admin-factory v0.2.0 (/home/runner/work/dao-contracts/dao-contracts/contracts/cw-admin-factory)`
versions that meet the …
```
> Stop using a git dependency for cw-multitest

- typescript/package.json
- typescript/src/codegen.ts
- typescript/tsconfig.json
- typescript/yarn.lock
ts-codegen's util.readSchemas function uses glob, which can't handle schema paths with back slashes from windows.
https://www.npmjs.com/package/glob - Windows Section
> Convert schemaDir back slashes into forward slashes for windows

- CONTRIBUTING.md
Running `just gen-typescript` would fail to generate schemas because of `String.replaceAll()` being unsupported for Node.js versions below v15.
https://github.com/DA0-DA0/dao-contracts/blob/1a2accbb425ba928845fa0a0f4231cb1fe9824a6/typescript/src/codegen.ts#L109
> node dev dependency

- .github/workflows/integration_tests.yml
I noticed the main gas file download broke after the name change PR merged: https://github.com/DA0-DA0/dao-contracts/actions/runs/3230162112/jobs/5288290668#step:13:24
But also, this PR will also pull in @0xekez 's fix from the cw-nfts PR (where it wasnt actually gracefully failing if the main's gas file wasn't found).
> Fix Gas Diff

- Cargo.lock
- contracts/cwd-core/src/msg.rs
- contracts/proposal/cwd-proposal-multiple/src/msg.rs
- contracts/proposal/cwd-proposal-single/src/msg.rs
- contracts/voting/cwd-voting-cw20-staked/src/msg.rs
- contracts/voting/cwd-voting-cw4/src/msg.rs
- contracts/voting/cwd-voting-cw721-staked/src/msg.rs
- contracts/voting/cwd-voting-native-staked/src/msg.rs
- contracts/voting/cwd-voting-staking-denom-staked/src/msg.rs
- packages/cwd-interface/src/voting.rs
- packages/cwd-macros/src/lib.rs
- packages/cwd-macros/tests/govmod.rs
- packages/cwd-macros/tests/voting.rs
- test-contracts/cwd-proposal-sudo/src/msg.rs
- test-contracts/cwd-voting-cw20-balance/src/msg.rs
deduplicates the macro code a fair bit and makes it more hygenic by using absolute paths for imports.
> Refactor macro code for better hygiene.

- contracts/voting/cwd-voting-cw721-staked/src/error.rs
- contracts/voting/cwd-voting-cw721-staked/src/testing/adversarial.rs
- contracts/voting/cwd-voting-cw721-staked/src/testing/instantiate.rs
- contracts/voting/cwd-voting-cw721-staked/src/testing/mod.rs
- contracts/voting/cwd-voting-cw721-staked/src/testing/tests.rs
This adds some adversarial tests to the cw721 stake voting module which focus on making sure it correctly updates voting power in the face of strange query and staking events.
> Simple adversarial tests for cw721 staking.

- contracts/pre-propose/cwd-pre-propose-multiple/schema/cwd-pre-propose-multiple.json
- contracts/pre-propose/cwd-pre-propose-multiple/src/tests.rs
- contracts/proposal/cwd-proposal-multiple/schema/cwd-proposal-multiple.json
- contracts/proposal/cwd-proposal-multiple/src/contract.rs
- contracts/proposal/cwd-proposal-multiple/src/msg.rs
- contracts/proposal/cwd-proposal-multiple/src/proposal.rs
- contracts/proposal/cwd-proposal-multiple/src/testing/do_votes.rs
- contracts/proposal/cwd-proposal-multiple/src/testing/tests.rs
- contracts/proposal/cwd-proposal-single/schema/cwd-proposal-single.json
- contracts/proposal/cwd-proposal-single/src/msg.rs
- packages/cwd-voting/src/multiple_choice.rs
- typescript/contracts/cwd-pre-propose-multiple/CwdPreProposeMultiple.types.ts
- typescript/contracts/cwd-proposal-multiple/CwdProposalMultiple.client.ts
- typescript/contracts/cwd-proposal-multiple/CwdProposalMultiple.types.ts
- typescript/contracts/cwd-proposal-single/CwdProposalSingle.client.ts
Some stuff that is coming up as I work on the frontend (there may be more, but want to get this in)
- fix a couple return type annotations
- simplify proposal.msgs type
- allow multiple choice options to have their own titles
- increase the max number of options
> multiple choice cleanups for frontend

- contracts/pre-propose/cwd-pre-propose-approval-single/Cargo.toml
- contracts/pre-propose/cwd-pre-propose-approval-single/src/contract.rs
- contracts/pre-propose/cwd-pre-propose-approval-single/src/msg.rs
- contracts/pre-propose/cwd-pre-propose-approval-single/src/state.rs
- contracts/pre-propose/cwd-pre-propose-approval-single/src/tests.rs
- contracts/pre-propose/cwd-pre-propose-approver/schema/cwd-pre-propose-approver.json
- contracts/pre-propose/cwd-pre-propose-approver/src/contract.rs
- contracts/pre-propose/cwd-pre-propose-approver/src/tests.rs
- contracts/pre-propose/cwd-pre-propose-single/Cargo.toml
- contracts/pre-propose/cwd-pre-propose-single/schema/cwd-pre-propose-single.json
- contracts/pre-propose/cwd-pre-propose-single/src/contract.rs
- contracts/proposal/cwd-proposal-single/Cargo.toml
- contracts/proposal/cwd-proposal-single/schema/cwd-proposal-single.json
- contracts/proposal/cwd-proposal-single/src/contract.rs
- contracts/proposal/cwd-proposal-single/src/msg.rs
- contracts/proposal/cwd-proposal-single/src/testing/execute.rs
- contracts/proposal/cwd-proposal-single/src/testing/tests.rs
- packages/cwd-pre-propose-base/src/execute.rs
- test-contracts/cwd-proposal-hook-counter/src/tests.rs
- typescript/contracts/cwd-pre-propose-approver/CwdPreProposeApprover.types.ts
- typescript/contracts/cwd-proposal-single/CwdProposalSingle.client.ts
- typescript/contracts/cwd-proposal-single/CwdProposalSingle.types.ts
This resolves a bug where if the approval pre-propose contract was added to a proposal module with pending proposals it would cause the wrong deposits to get refunded. The bug is discussed in detail in https://github.com/DA0-DA0/dao-contracts/pull/536#discussion_r1028507568.
Still WIP because I want to write a couple more tests.
There are two phases:
1. The approval phase. If the proposal is approved, the deposit moves to phase 2. If the proposal is rejected, unless all deposits are being refunded, the deposit is sent to the DAO.
2. The deposit phase. This works like the proposal deposit system we are familiar with and is the one implemented in cwd-pre-propose-base.
To create a new proposal:
1. Make sure the deposit has been paid.
2. Generate a new approval ID.
3. Map that approval ID to …
> Allow pre-propose approval contract to be added to a proposal module with pending proposals

- contracts/staking/cw20-stake/src/contract.rs
- contracts/staking/cw20-stake/src/error.rs
- contracts/staking/cw20-stake/src/lib.rs
- contracts/staking/cw20-stake/src/math.rs
this fixes a fairly pathological, non-severe, integer overflow bug in the stake-cw20 contract. after discussion with ben2x4, meow, and bluenote, we've decided that this bug is extremely unlikely to be reached in production; if it is reached, it is entirely recoverable. as such, i'm making the patch public.
see here for a description of the bug, and a recovery strategy should anyone ever hit it:
https://github.com/DA0-DA0/dao-contracts/wiki/Overflow-in-stake-cw20
once this lands, i'll work on some detailed upgrade instructions for DAO DAO DAOs. it is nice we have a bug like this, because it is a great chance to get DAOs practicing doing upgrades in a safe environment. we can run a fire drill next week for DAOs that would like to participate and help them practice upgrading.
> Formally verify and fix overflow in cw20-stake stake and unstake methods

- contracts/dao-core/src/contract.rs
- contracts/pre-propose/dao-pre-propose-approval-single/src/contract.rs
- contracts/pre-propose/dao-pre-propose-approval-single/src/state.rs
- contracts/proposal/dao-proposal-single/schema/dao-proposal-single.json
- contracts/proposal/dao-proposal-single/src/msg.rs
it is unclear to me if this would ever be a problem, but i feel it may be best to err on the side of caution here in the event that we ever want to use the data field in a TX that involves instantiating a DAO that doesn't use it itself.
> Don't error if res.data isn't marshallable into a callback.

- contracts/proposal/dao-proposal-single/src/proposal.rs
I came across this method when reviewing [this indexer code](https://github.com/NoahSaso/wasmd-indexer/blob/main/src/core/formulas/proposal/daoProposalSingle.ts#L210-L226). I had to reason through this comment a bit more than I should have.
This PR clarifies (rather, frames in my understanding) what this method does.
> Update comment explaining `into_response`

- contracts/voting/dao-voting-cw721-staked/src/contract.rs
- contracts/voting/dao-voting-cw721-staked/src/state.rs
- contracts/voting/dao-voting-cw721-staked/src/testing/adversarial.rs
- packages/cw721-controllers/src/nft_claim.rs
resolves #580 
Previously one could bypass `MAX_CLAIMS` by unstaking more than one NFT in a single TX.
> Consider unstaking tokens when checking MAX_CLAIMS invariant.

- contracts/proposal/dao-proposal-multiple/src/contract.rs
- contracts/proposal/dao-proposal-multiple/src/testing/queries.rs
- contracts/proposal/dao-proposal-multiple/src/testing/tests.rs
- contracts/proposal/dao-proposal-single/src/contract.rs
- contracts/proposal/dao-proposal-single/src/testing/tests.rs
Resolves #575 
This makes it so that `only_members_execute` uses the voting power at time of proposal creation to validate membership during execution instead of at the current time.
> Use voting power at time of proposal creation for only_members_execute

- Cargo.lock
- contracts/dao-core/Cargo.toml
- contracts/proposal/dao-proposal-single/Cargo.toml
- contracts/proposal/dao-proposal-single/src/testing/migration_tests.rs
- contracts/proposal/dao-proposal-single/src/testing/mod.rs
- contracts/proposal/dao-proposal-single/src/testing/queries.rs
- packages/dao-testing/Cargo.toml
- packages/dao-testing/src/contracts.rs
This tests the migration of a v1 DAO with multiple proposals, items, tokens in it's treasury, and one proposal that is in an open-but-not-executable state to v2.
> Add test for complex v1 to v2 migration

- contracts/external/cw-vesting/README.md
Changed `CW Payroll` to `CW Vesting` in line with the contract name.
> Update title of cw-vesting README

- contracts/external/cw-payroll-factory/schema/cw-payroll-factory.json
- contracts/external/cw-payroll-factory/src/msg.rs
- typescript/contracts/cw-payroll-factory/CwPayrollFactory.client.ts
- typescript/contracts/cw-payroll-factory/CwPayrollFactory.types.ts
The `cw-payroll-factory` list queries seem to return lists of `VestingContract` structs, not `Addr`s. This PR updates the schema to match the queries.
> Fix cw-payroll-factory query schema

- README.md
- packages/cw-denom/src/lib.rs
Line 19 - URL was pointing to contracts/staking/cw20-stake-external-rewards Changed to contracts/staking/cw20-stake-reward-distributor
> Update URL for cw20-stake-reward-distributor

- contracts/pre-propose/dao-pre-propose-multiple/src/tests.rs
- contracts/proposal/dao-proposal-multiple/schema/dao-proposal-multiple.json
- contracts/proposal/dao-proposal-multiple/src/contract.rs
- contracts/proposal/dao-proposal-multiple/src/error.rs
- contracts/proposal/dao-proposal-multiple/src/msg.rs
- contracts/proposal/dao-proposal-multiple/src/query.rs
- contracts/proposal/dao-proposal-multiple/src/state.rs
- contracts/proposal/dao-proposal-multiple/src/testing/adversarial_tests.rs
- contracts/proposal/dao-proposal-multiple/src/testing/do_votes.rs
- contracts/proposal/dao-proposal-multiple/src/testing/tests.rs
- packages/cw-denom/src/lib.rs
- packages/dao-voting/src/voting.rs
- typescript/contracts/dao-proposal-multiple/DaoProposalMultiple.client.ts
- typescript/contracts/dao-proposal-multiple/DaoProposalMultiple.types.ts
also cleans up a duplicated MultipleChoiceVote type 
I wanted to get this in before frontend changes land because it is easier without having to worry about migration
> add update rationale to multiple choice contract

- Cargo.lock
- contracts/external/cw-abc/Cargo.toml
- contracts/external/cw-abc/src/abc.rs
- contracts/external/cw-abc/src/commands.rs
- contracts/external/cw-abc/src/contract.rs
- contracts/external/cw-abc/src/error.rs
- contracts/external/cw-abc/src/lib.rs
- contracts/external/cw-abc/src/msg.rs
- contracts/external/cw-abc/src/queries.rs
- contracts/external/cw-abc/src/state.rs
This change does the following:
- initial phase configuration setup for cw-abc
- phase configurations and current phase stored in state
- Hatch phase has an allowlist
- Basic phase queries
- cw-ownable integration
- Move queries & commands to `queries` and `commands` respectively
- Addition of `funding` pool to the curve state
There are TODOs where functionality is still missing. The burn mechanism was left untouched.
Questions: 
1) Do we want to have a `PreHatch` phase where the configuration can be changed freely? Hatch configuration for the `initialPrice` should NOT be changed after the phase has begun, though the `min` and `max` `initialRaise` should be able to be changed (like in traditional fundraising)
2) Do we want to separate the phase configurations into their own states so that …
> Initial phase integration to cw-abc

- Cargo.lock
- contracts/external/cw-abc/Cargo.toml
- contracts/external/cw-abc/src/abc.rs
- contracts/external/cw-abc/src/boot.rs
- contracts/external/cw-abc/src/commands.rs
- contracts/external/cw-abc/src/contract.rs
- contracts/external/cw-abc/src/error.rs
- contracts/external/cw-abc/src/integration.rs
- contracts/external/cw-abc/src/lib.rs
- contracts/external/cw-abc/src/msg.rs
- contracts/external/cw-abc/src/queries.rs
- contracts/external/cw-abc/src/state.rs
This change implements the following:
1) Donation feature for donating tokens directly to the funding pool
- Keeps track of donations and is queryable
2) Initial sell exit-tax implementation 
- Q: do we want hatchers to be able to sell their tokens at all? Right now there is an exit tax functionality but it would allow early investors to dump on later investors. Maybe we should require it to be > 50%?
3) Hatchers are tracked in a `Map` to allow for vesting schedule checking, otherwise their tokens bought afterwards would be stuck in their same vesting schedule
- Queryable
4) Update phase config
5) Initial boot integration and testing infra setup
- TODO: we need to make a PR to the `token-bindings` so that we can have a custom handler for the TokenFactory.
> cw-abc: Updated hatch phase mechanics, donations, queries

- .github/workflows/basic.yml
- .github/workflows/codecov.yml
- .github/workflows/integration_tests.yml
- contracts/proposal/dao-proposal-condorcet/src/testing/suite.rs
- contracts/proposal/dao-proposal-multiple/src/testing/instantiate.rs
- contracts/proposal/dao-proposal-single/src/testing/instantiate.rs
- contracts/voting/dao-voting-cw4/schema/dao-voting-cw4.json
- contracts/voting/dao-voting-cw4/src/contract.rs
- contracts/voting/dao-voting-cw4/src/error.rs
- contracts/voting/dao-voting-cw4/src/msg.rs
- contracts/voting/dao-voting-cw4/src/tests.rs
- packages/dao-testing/src/helpers.rs
> Dao voting cw4 cleanup
