DA0-DA0/dao-contracts

- src/contract.rs
- src/msg.rs
- src/query.rs
This PR add a query to get the config. Closes https://github.com/JakeHartnell/cw-dao/issues/6
> Get config query

- README.md
- contracts/cw-dao/src/msg.rs
- scripts/deploy.sh
> First draft of deploy script + docs

- docker/app.toml
- scripts/deploy_local.sh
This starts the rest API and disables CORS
> custom app.toml for docker wasmd

- scripts/mock_treasury.sh
- creates `EARTH`, `MOON`, & `SUN` tokens
- transfers the above tokens to CW-DAO contract in varying amounts
usage: `bash scripts/mock_treasury.sh $CW_DAO_CONTACT_ADDRESS`
> Mock treasure data

- contracts/cw3-dao/src/contract.rs
- contracts/cw3-dao/src/tests.rs
- contracts/cw3-multisig/src/contract.rs
- contracts/cw3-multisig/src/tests.rs
Addresses #161 
Add the contract change, in the linked PR.
Also implement the tests they added.
> cw3-flex-multisig fixes

- contracts/stake-cw20-external-rewards/examples/schema.rs
- contracts/stake-cw20-external-rewards/schema/info_response.json
- contracts/stake-cw20-external-rewards/schema/pending_rewards_response.json
- contracts/stake-cw20-external-rewards/src/contract.rs
- contracts/stake-cw20-external-rewards/src/error.rs
- contracts/stake-cw20-external-rewards/src/state.rs
Basic cleanup for staking rewards contract
> Vt staking rewards revisions

- scripts/deploy_local.sh
InstantiateMsg for cw3 dao contract had some new fields added recently
> fix local deploy script 

- contracts/cw-governance/src/helpers.rs
- contracts/cw-governance/src/msg.rs
- contracts/cw-govmod-single/src/msg.rs
- contracts/cw-govmod-single/src/state.rs
- contracts/cw-govmod-single/src/tests.rs
> Consistent use of `Name {}` style enums.

- contracts/cw20-staked-balance-voting/src/contract.rs
Fix oversight in previous PR #212
> Fixed staked token creation without any initial non-DAO owners

- contracts/cw-govmod-single/src/proposal.rs
- contracts/cw-govmod-single/src/tests.rs
- packages/voting/src/lib.rs
This updates the rejection logic so that proposals are considered
rejected if the number of no votes > 100% - threshold.
This also adds a number of tests that check our behavior in the event
that a proposal results in a tie or a proposal has only abstain
votes. The current behavior, and the behavior of the old contracts is
to pass the proposal in both cases. We should do some deep thinking
about if this is the desired behavior.
> v1 contracts - Properly determine if a proposal is rejected.

- contracts/cw20-staked-balance-voting/src/contract.rs
- contracts/cw20-staked-balance-voting/src/error.rs
- contracts/cw20-staked-balance-voting/src/msg.rs
- contracts/cw20-staked-balance-voting/src/state.rs
- contracts/cw20-staked-balance-voting/src/tests.rs
- packages/cw-core-interface/src/voting.rs
- packages/cw-core-macros/src/lib.rs
Closes https://github.com/DA0-DA0/dao-contracts/issues/246
Allows voting modules to support an IsActive {} query route which can return true or false if the DAO is allowed to create proposals or not.
Feedback appreciated.
> Active query

- contracts/cw-proposal-single/src/tests.rs
Handled correctly previously, but not tested. Now it's tested. :)
> Add test for a zero token deposit.

- contracts/cw-core/src/contract.rs
- contracts/cw-core/src/msg.rs
- contracts/cw-core/src/tests.rs
- contracts/cw-proposal-single/src/tests.rs
> Rename `UpdateGovernanceModules` -> `UpdateProposalModules`.

- contracts/cw4-voting/src/tests.rs
- Tests that new weights are not reflected until the block increasing the weight is done.
- Tests that permissions are properly managed on the member update hook.
> Add permissions and block after test to cw4-groups contract.

- README.md
- contracts/cw-core/README
- contracts/cw-proposal-single/README
- contracts/cw20-staked-balance-voting/README.md
- contracts/cw4-voting/README.md
To add a README branch off of this branch and open a PR to do so, will move from draft to R4R when we believe we have reached a good amount of coverage.
> ADD READMES

- contracts/cw-proposal-single/schema/config_response.json
- contracts/cw-proposal-single/schema/execute_msg.json
- contracts/cw-proposal-single/schema/instantiate_msg.json
- contracts/cw-proposal-single/schema/list_proposals_response.json
- contracts/cw-proposal-single/schema/proposal_response.json
- contracts/cw-proposal-single/schema/reverse_proposals_response.json
- contracts/cw-proposal-single/src/proposal.rs
- contracts/cw-proposal-single/src/tests.rs
- packages/voting/src/threshold.rs
Resolves #239 .
Adds an absolute count passing threshold which takes ~20 lines of code and then a large number of tests.
> Add absolute count passing threshold.

- .github/workflows/basic.yml
- README.md
- contracts/cw-named-groups/schema/execute_msg.json
- contracts/cw-named-groups/schema/query_msg.json
- contracts/cw20-staked-balance-voting/schema/execute_msg.json
- contracts/cw20-staked-balance-voting/schema/instantiate_msg.json
- contracts/cw20-staked-balance-voting/schema/query_msg.json
- scripts/schema.sh
Helper script to check schema diff on each commit
> Add Schema Diff Checker Workflow

- contracts/cw-core/examples/schema.rs
- contracts/cw-core/schema/admin_response.json
- contracts/cw-core/schema/dump_state_response.json
- contracts/cw-core/schema/execute_msg.json
- contracts/cw-core/schema/instantiate_msg.json
- contracts/cw-core/schema/query_msg.json
- contracts/cw-core/src/contract.rs
- contracts/cw-core/src/error.rs
- contracts/cw-core/src/msg.rs
- contracts/cw-core/src/query.rs
- contracts/cw-core/src/state.rs
- contracts/cw-core/src/tests.rs
- contracts/cw-proposal-single/src/staking_tests.rs
- contracts/cw-proposal-single/src/tests.rs
- debug/proposal-hooks-counter/src/tests.rs
> Implement optional admins for SubDAOs

- contracts/cw4-voting/src/contract.rs
- contracts/cw4-voting/src/error.rs
- contracts/cw4-voting/src/tests.rs
Patch issue 1 from our Oak Security audit.
> Dedup duplicates

- contracts/cw20-staked-balance-voting/src/contract.rs
- contracts/cw20-staked-balance-voting/src/tests.rs
This should fix issue 9 of the audit. CC @Callum-A 
Close #331
> Address issue 9 of the audit report

- contracts/stake-cw20-external-rewards/src/contract.rs
> Address issue 13 of audit report

- contracts/cw-core/src/contract.rs
- contracts/cw-core/src/error.rs
- contracts/cw-core/src/tests.rs
@Callum-A / @ezekiiel  I was thinking of calling `add_attribute("key_removed", key_removed)` in the response to indicate if the key was actually removed, but it was not clear if it would be useful information
Close #325
> Address issue 3 of the audit report

- contracts/cw-core/schema/config_response.json
- contracts/cw-core/schema/dump_state_response.json
- contracts/cw-core/schema/execute_msg.json
- contracts/cw-core/schema/instantiate_msg.json
- contracts/cw-core/src/lib.rs
- contracts/cw-core/src/msg.rs
- contracts/cw-core/src/state.rs
- contracts/cw-proposal-single/schema/execute_msg.json
- contracts/cw-proposal-single/schema/list_proposals_response.json
- contracts/cw-proposal-single/schema/proposal_response.json
- contracts/cw-proposal-single/schema/query_msg.json
- contracts/cw-proposal-single/schema/reverse_proposals_response.json
- contracts/cw-proposal-single/src/lib.rs
- contracts/cw-proposal-single/src/msg.rs
- contracts/cw-proposal-single/src/query.rs
- contracts/cw-proposal-single/src/state.rs
This adds some module level documentation to cw-core and cw-proposal-single. This will be nice to have once we publish cargo packages.
> Improve some documentation in cw-core and cw-proposal-single.

- contracts/cw20-stake/examples/schema.rs
- contracts/cw20-stake/schema/get_config_response.json
- contracts/cw20-stake/src/contract.rs
- contracts/cw20-stake/src/error.rs
- contracts/cw20-stake/src/msg.rs
- contracts/cw20-staked-balance-voting/src/contract.rs
- types/contracts/cw20-stake/Cw20StakeContract.ts
> Return Config directly and validate duration in cw20-stake

- contracts/cw20-stake/src/tests.rs
Wrote this during a fit of paranoia this morning. Everything is OK and works as expected. Figured we may as well add the test.
> Add test for SnapshotMap behavior during unstaking.

- packages/cw-paginate/README.md
- packages/cw-paginate/src/lib.rs
Will be nice for when we publish on crates.io.
> Add package documentation for cw-paginate.

- contracts/cw-core/src/contract.rs
- contracts/cw-core/src/tests.rs
This performs some basic validation for cw20 and cw721 tokens added to the cw-core treasury. This is in response to an issue reported where a user added a cw721 and broke the `Cw20Balances` query.
Resolves #427
> Basic validation for cw20 and cw721 contracts added to treasury.

- contracts/cw-proposal-multiple/src/contract.rs
- contracts/cw-proposal-multiple/src/tests.rs
We did forget something in #385... I'm so sorry @ezekiiel.
> Small fix of close_proposal_on_execution_failure feature

- CONTRIBUTING.md
Based on feedback from Whisky.
> Improve documentation about generating schema files.

- contracts/cw-admin-factory/Cargo.toml
- contracts/cw-admin-factory/NOTICE
- contracts/cw-named-groups/Cargo.toml
- contracts/cw-named-groups/NOTICE
- contracts/cw-proposal-multiple/Cargo.toml
- contracts/cw-proposal-multiple/NOTICE
- contracts/cw-proposal-multiple/schema/list_proposals_response.json
- contracts/cw-proposal-multiple/schema/proposal_response.json
- contracts/cw-proposal-multiple/schema/reverse_proposals_response.json
- contracts/cw-proposal-multiple/src/contract.rs
- contracts/cw-proposal-multiple/src/proposal.rs
- contracts/cw-proposal-multiple/src/tests.rs
- contracts/cw-proposal-single/schema/list_proposals_response.json
- contracts/cw-proposal-single/schema/proposal_response.json
- contracts/cw-proposal-single/schema/reverse_proposals_response.json
- contracts/cw-proposal-single/src/contract.rs
- contracts/cw-proposal-single/src/proposal.rs
- contracts/cw-proposal-single/src/tests.rs
- types/contracts/cw-proposal-multiple/CwProposalMultipleContract.ts
> add timestamps to multiple choice proposals 

- .github/workflows/integration_tests.yml
closes https://github.com/DA0-DA0/dao-contracts/issues/403
Now we will post the gas report of each commit and showcase any operation that has a gas diff larger than +/- 0.5% above the fold.
> Add gas diff PR comment

- contracts/cw-core/schema/dump_state_response.json
- contracts/cw-core/src/contract.rs
- contracts/cw-core/src/query.rs
- contracts/cw-core/src/state.rs
- contracts/cw-core/src/tests.rs
- types/contracts/cw-core/CwCoreContract.ts
> add DAO created timestamp

- Cargo.lock
- ci/integration_tests/Cargo.toml
- ci/integration_tests/README.md
- ci/integration_tests/src/tests/cw20_stake_test.rs
We were sleeping 5 seconds here before I commented it out because it was flakey.
> Fix flakey execute_stake_tokens integration test

- contracts/proposal/cwd-proposal-multiple/README.md
- contracts/proposal/cwd-proposal-single/README.md
> Update proposal module README titles.

- contracts/pre-propose/dao-pre-propose-approval-single/src/contract.rs
- contracts/pre-propose/dao-pre-propose-approval-single/src/state.rs
- contracts/proposal/dao-proposal-single/schema/dao-proposal-single.json
- contracts/proposal/dao-proposal-single/src/msg.rs
This is slightly less space efficent than the way it was, but I feel we can sacrifice space efficency a little for safer typing.
> Add `proposer` field to `PendingProposal`.

- README.md
- contracts/README.md
- contracts/dao-core/README.md
- contracts/pre-propose/dao-pre-propose-approval-single/README.md
- contracts/pre-propose/dao-pre-propose-approval-single/src/lib.rs
- contracts/pre-propose/dao-pre-propose-approver/README.md
- contracts/pre-propose/dao-pre-propose-approver/src/lib.rs
- contracts/proposal/dao-proposal-multiple/README.md
- contracts/proposal/dao-proposal-single/README.md
- contracts/voting/dao-voting-cw20-staked/README.md
- contracts/voting/dao-voting-cw4/README.md
- contracts/voting/dao-voting-native-staked/README.md
- contracts/voting/dao-voting-staking-denom-staked/README.md
- packages/dao-pre-propose-base/README.md
- packages/dao-proposal-hooks/README.md
- packages/dao-vote-hooks/README.md
Fixing up a few docs related things as I find them.
> Docs cleanup

- Cargo.lock
- ci/integration-tests/src/tests/cw_core_test.rs
- contracts/dao-core/schema/dao-core.json
- contracts/dao-core/src/contract.rs
- contracts/dao-core/src/msg.rs
- contracts/dao-core/src/tests.rs
- contracts/pre-propose/dao-pre-propose-approval-single/src/contract.rs
- contracts/pre-propose/dao-pre-propose-single/Cargo.toml
- contracts/pre-propose/dao-pre-propose-single/src/tests.rs
- packages/dao-pre-propose-base/src/execute.rs
- packages/dao-pre-propose-base/src/lib.rs
- packages/dao-pre-propose-base/src/tests.rs
- typescript/contracts/dao-core/DaoCore.client.ts
- typescript/contracts/dao-core/DaoCore.types.ts
Updates an outdated name in the `SetItem` message and adds some tests for various things.
> Various little cleanups

- README.md
- contracts/README.md
- contracts/dao-core/README.md
- contracts/pre-propose/dao-pre-propose-approval-single/README.md
- contracts/pre-propose/dao-pre-propose-approval-single/src/lib.rs
- contracts/pre-propose/dao-pre-propose-approver/README.md
- contracts/pre-propose/dao-pre-propose-approver/src/lib.rs
- contracts/proposal/dao-proposal-multiple/README.md
- contracts/proposal/dao-proposal-single/README.md
- contracts/voting/dao-voting-cw20-staked/README.md
- contracts/voting/dao-voting-cw4/README.md
- contracts/voting/dao-voting-native-staked/README.md
- contracts/voting/dao-voting-staking-denom-staked/README.md
- packages/dao-pre-propose-base/README.md
- packages/dao-proposal-hooks/README.md
- packages/dao-vote-hooks/README.md
> Docs Cleanup 2

- contracts/dao-core/schema/dao-core.json
- contracts/dao-core/src/contract.rs
- contracts/dao-core/src/msg.rs
- contracts/dao-core/src/query.rs
- contracts/dao-core/src/state.rs
- contracts/dao-core/src/tests.rs
- typescript/contracts/dao-core/DaoCore.client.ts
- typescript/contracts/dao-core/DaoCore.types.ts
> Add ProposalModuleCount query.

- contracts/voting/dao-voting-cw20-staked/src/contract.rs
- contracts/voting/dao-voting-cw20-staked/src/error.rs
- contracts/voting/dao-voting-cw20-staked/src/tests.rs
> Validate absolute count active threshold to be non-zero.

- contracts/voting/dao-voting-cw20-staked/src/contract.rs
> Remove unneeded negative decimal validation.

- contracts/voting/dao-voting-native-staked/src/contract.rs
- contracts/voting/dao-voting-native-staked/src/error.rs
- contracts/voting/dao-voting-native-staked/src/tests.rs
> Require unstaking amount to be non-zero.

- contracts/dao-core/schema/dao-core.json
- contracts/dao-core/src/contract.rs
- contracts/dao-core/src/error.rs
- contracts/dao-core/src/msg.rs
- contracts/dao-core/src/tests.rs
> Disallow duplicate items during instantiation.

- contracts/staking/cw20-stake/src/contract.rs
- contracts/staking/cw20-stake/src/error.rs
- contracts/staking/cw20-stake/src/tests.rs
> Check cw20 responds to TokenInfo query during cw20-stake instantiation.

- contracts/dao-core/src/contract.rs
- contracts/dao-core/src/error.rs
- contracts/dao-core/src/tests.rs
- contracts/proposal/dao-proposal-single/src/contract.rs
- contracts/proposal/dao-proposal-single/src/error.rs
- contracts/proposal/dao-proposal-single/src/testing/tests.rs
> Require that from_v1 migrations are not from v2.

- CONTRIBUTING.md
- ci/integration-tests/README.md
- contracts/dao-core/README.md
- contracts/dao-core/schema/dao-core.json
- contracts/dao-core/src/msg.rs
> Fix: typos

- README.md
In readme file:
- Fix a typo
- Format the tables
> Fix a typo and format README

- contracts/external/cw-vesting/src/tests.rs
i'm not really sure how this got in on the PR without causing clippy to fail there.
> Clippy, one of the great mysteries of life.

- README.md
- contracts/external/cw-vesting/README.md
Got overridden in a force push: https://github.com/DA0-DA0/dao-contracts/compare/1920dd74e90712ac235b8bb07e13786caf4b8f59..65e098695e68eb9597414651da0e33d044beffd2
> Add a bunch more info to the `cw-vesting` README

- contracts/proposal/dao-proposal-multiple/src/contract.rs
Rebased #636 so linting passes.
> Handle callback messages from preproposal contracts

- contracts/external/cw-vesting/README.md
Pretty ez, self-explanatory PR. Little fixes as I read this over.
So stoked for this contract!!1
> Fix minor typos in exciting cw-vesting contract's README

- contracts/dao-core/schema/dao-core.json
- contracts/dao-core/src/migrate_msg.rs
- contracts/external/dao-migrator/src/contract.rs
- contracts/external/dao-migrator/src/error.rs
- contracts/external/dao-migrator/src/testing/helpers.rs
- contracts/external/dao-migrator/src/testing/setup.rs
- contracts/external/dao-migrator/src/testing/test_migration.rs
- contracts/external/dao-migrator/src/types.rs
- typescript/contracts/dao-core/DaoCore.types.ts
Fixed the issue, and added a specific test to the error we were getting
> Fix migrator

- ci/integration-tests/src/helpers/helper.rs
- ci/integration-tests/src/tests/dao_voting_cw721_staked_test.rs
- ci/integration-tests/src/tests/mod.rs
- ci/integration-tests/src/tests/proposal_gas_test.rs
- justfile
based on tuning on my local setup, the current number is 55.
> Integration test to measure max NFTs mintable in a single proposal.

- contracts/external/cw-vesting/README.md
Discussed [on Twitter](https://twitter.com/RealInterchain/status/1630773295896207360?s=20).
> Add attribution section to cw-vesting README.

- contracts/external/cw-vesting/src/contract.rs
Resolves issue five of the Oak Security cw-vesting audit report.
> Emit attributes during undelegation.

- contracts/external/cw-payroll-factory/src/contract.rs
- contracts/external/cw-payroll-factory/src/error.rs
- contracts/external/cw-payroll-factory/src/tests.rs
Resolves the second issue in the oak cw-vesting audit report.
> Check cw20 funding amount in cw-payroll-factory.

- contracts/external/cw-fund-distributor/src/contract.rs
- contracts/external/cw-fund-distributor/src/error.rs
- contracts/external/cw-fund-distributor/src/testing/tests.rs
Iterates on the #609 with some improvements:
- removing all `unwraps`
- reviewed tests
- slight touches on re-distributor
- makes `clippy` happy
> cw-distributor rework

- Cargo.lock
- Cargo.toml
- contracts/external/dao-migrator/src/contract.rs
- contracts/external/dao-migrator/src/testing/helpers.rs
- contracts/external/dao-migrator/src/testing/setup.rs
- contracts/external/dao-migrator/src/testing/test_migration.rs
- packages/dao-testing/Cargo.toml
- packages/dao-testing/src/contracts.rs
> prepare migrator to v2.1

- packages/dao-voting/src/threshold.rs
- packages/dao-voting/src/voting.rs
> chore: rename arg on counting pass

- .github/workflows/release-contracts.yml
following: [this tweet](https://twitter.com/albttx/status/1621203943773687809) i realized DAO-DAO contracts wan't build though the CI,
Here is a Github action for that
> chore(ci): action release-contracts
